apps:
  - script   : ./app.js
    name     : '{{name}}'
    instances: 0
    exec_mode: cluster
    max_memory_restart: 1G
    watch  : true
    env    :
      NODE_ENV: development
    env_production:
      NODE_ENV: production
